### ISSUE TITLE
hi，关于多状态布局的参考

### ISSUE THREAD

**Issue by fanturbo** [ditclear/StateBinding#1]
在简书上看到一篇文章https://www.jianshu.com/p/be740a2eab3a，联系不上那个作者，想问下你对那篇文章的话有什么理解没？好像使用他的方法避免了再每个子布局中频繁的include布局了。

**Comment by ditclear** [comment]
StateBinding这个项目时间蛮久了，include 应该算是比较直接的方法，但是写的代码有点多。
现在我对于多状态布局 还是建议 用一个StateLayout为好，里面封装好各种状态，然后只需要根据State显示就好,具体 可以通过 stateLayout.showEmpty（）或者通过数据绑定、LiveData来更新

**Comment by fanturbo** [comment]
@ditclear 额，封装好的Statelayout只是在一个将include中所有布局都封装到一个ViewGroup中了，与include并没有什么区别啊，现在你的项目中的include这种方式也是通过数据绑定来展示的各种状态啊

**Comment by ditclear** [comment]
封装好的好处就是能直接让组内的其它同事使用，不需要关心细节

**Comment by fanturbo** [comment]
那其实也是需要每个布局中去单独加上的对吗

**Comment by ditclear** [comment]
是的，但会减轻一些工作量------------------ 原始邮件 ------------------
发件人: "fanturbo"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 下午2:01
收件人: "ditclear/StateBinding"<StateBinding@noreply.github.com>;
抄送: "D&#x2022;IT&#x2022;CLEAR"<ditclear@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ditclear/StateBinding] hi，关于多状态布局的参考 (#1)



那其实也是需要每个布局中去单独加上的对吗
 
&mdash;

**Comment by fanturbo** [comment]
好的，thanks.

**Comment by fanturbo** [comment]
hello,我发现了一个问题哈，因为我原先也是使用的这种封装好的组合布局（包括空、网络错误或者其他错误），然后在每一个单独的页面单独调用这个组合布局的方法（比如设置空或者错误），但是我发现如果使用GitHubBrowserSample这个demo中的方式（也就是你的这个项目里的方式）的话，虽然在xml中非常的繁琐，但是其实都是简单的复制粘贴，因为使用了databinding，可以把这个处理抽取到网络请求中，不需要每个页面单独去处理了。这样是不是简单些了？额，问下你在实际项目中是如何处理的呢？

**Comment by ditclear** [comment]
我以前就是复制粘贴的，虽说简单，但是如果能封装好直接用的话还是建议封装的好，我认为View的状态应该交由其内部处理，外层传入一个值，View能够根据这个值显示对应的状态，感觉比较好点




------------------ 原始邮件 ------------------
发件人: "fanturbo"<notifications@github.com>; 
发送时间: 2019年7月1日(星期一) 下午3:04
收件人: "ditclear/StateBinding"<StateBinding@noreply.github.com>; 
抄送: "ditclear"<ditclear@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ditclear/StateBinding] hi，关于多状态布局的参考 (#1)




hello,我发现了一个问题哈，因为我原先也是使用的这种封装好的组合布局（包括空、网络错误或者其他错误），然后在每一个单独的页面单独调用这个组合布局的方法（比如设置空或者错误），但是我发现如果使用GitHubBrowserSample这个demo中的方式（也就是你的这个项目里的方式）的话，虽然在xml中非常的繁琐，但是其实都是简单的复制粘贴，因为使用了databinding，可以把这个处理抽取到网络请求中，不需要每个页面单独去处理了。这样是不是简单些了？额，问下你在实际项目中是如何处理的呢？

**Comment by fanturbo** [comment]
好的，thanks
